package cl.intelidata.amicar.componentes;

import cl.intelidata.amicar.referencias.Imagenes;
import cl.intelidata.amicar.referencias.Url;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.*;
import org.vaadin.kim.countdownclock.CountdownClock;
import org.vaadin.kim.countdownclock.CountdownClock.EndEventListener;

import java.util.Calendar;

public class Body extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 *
	 */
	private static final long serialVersionUID = 7868435926633644717L;
	@AutoGenerated private VerticalLayout mainLayout;
	@AutoGenerated private Panel          pnlContenido;
	@AutoGenerated private VerticalLayout vlPanel;
	@AutoGenerated private VerticalLayout vlContenido;
	@AutoGenerated private Embedded       imgFooter;
	@AutoGenerated private VerticalLayout vlMensaje;
	@AutoGenerated private Embedded       imgHeader;
	private                Label          lblMensaje;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	/*******************************************************************************************************/
	/*******************************************************************************************************/
	/**
	 * ***************************************************************************************************
	 */
	public Body() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.setImagen();
	}

	/*******************************************************************************************************/
	/*********************************************** Metodos ***********************************************/
	/**
	 * ***************************************************************************************************
	 */

	private void setImagen() {
		imgFooter.setSource(new ThemeResource(Imagenes.IMG_FOOTER));
		imgHeader.setSource(new ThemeResource(Imagenes.IMG_HEADER));
	}

	@SuppressWarnings("deprecation")
	public void setMensaje(String strMensaje, Integer segundos) {
		// lblMensaje
		if (segundos != null) {
			mensaje(strMensaje);
			CountdownClock clock = new CountdownClock();
			Calendar c = Calendar.getInstance();
			c.add(Calendar.SECOND, segundos);
			clock.setDate(c.getTime());
			clock.setFormat("<center><h3>Redirigiendo a http://www.amicar.cl en %s segundos.</h3><center>");

			clock.addListener(
					new EndEventListener() {
						public void countDownEnded(CountdownClock clock) {
							getUI().getPage().setLocation(Url.AMICAR);
						}
					}
			);

			vlMensaje.addComponent(clock);
			vlMensaje.setComponentAlignment(clock, Alignment.TOP_CENTER);

		} else {
			mensaje(strMensaje);
		}

	}

	private void mensaje(String strMensaje) {
		this.lblMensaje = new Label("<h3>" + strMensaje + "</h3>", ContentMode.HTML);
		this.lblMensaje.setImmediate(false);
		this.lblMensaje.setWidth("-1px");
		this.lblMensaje.setHeight("-1px");
		this.vlMensaje.addComponent(lblMensaje);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// pnlContenido
		pnlContenido = buildPnlContenido();
		mainLayout.addComponent(pnlContenido);

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPnlContenido() {
		// common part: create layout
		pnlContenido = new Panel();
		pnlContenido.setImmediate(false);
		pnlContenido.setWidth("100.0%");
		pnlContenido.setHeight("600px");

		// vlPanel
		vlPanel = buildVlPanel();
		pnlContenido.setContent(vlPanel);

		return pnlContenido;
	}

	@AutoGenerated
	private VerticalLayout buildVlPanel() {
		// common part: create layout
		vlPanel = new VerticalLayout();
		vlPanel.setImmediate(false);
		vlPanel.setWidth("100.0%");
		vlPanel.setHeight("100.0%");
		vlPanel.setMargin(false);

		// vlContenido
		vlContenido = buildVlContenido();
		vlPanel.addComponent(vlContenido);
		vlPanel.setComponentAlignment(vlContenido, new Alignment(20));

		return vlPanel;
	}

	@AutoGenerated
	private VerticalLayout buildVlContenido() {
		// common part: create layout
		vlContenido = new VerticalLayout();
		vlContenido.setImmediate(false);
		vlContenido.setWidth("670px");
		vlContenido.setHeight("-1px");
		vlContenido.setMargin(false);

		// imgHeader
		imgHeader = new Embedded();
		imgHeader.setImmediate(false);
		imgHeader.setWidth("-1px");
		imgHeader.setHeight("-1px");
		imgHeader.setSource(new ThemeResource("img/component/embedded_icon.png"));
		imgHeader.setType(1);
		imgHeader.setMimeType("image/png");
		vlContenido.addComponent(imgHeader);
		vlContenido.setComponentAlignment(imgHeader, new Alignment(20));

		// vlMensaje
		vlMensaje = new VerticalLayout();
		vlMensaje.setImmediate(false);
		vlMensaje.setWidth("-1px");
		vlMensaje.setHeight("-1px");
		vlMensaje.setMargin(false);
		vlContenido.addComponent(vlMensaje);
		vlContenido.setComponentAlignment(vlMensaje, new Alignment(20));

		// imgFooter
		imgFooter = new Embedded();
		imgFooter.setImmediate(false);
		imgFooter.setWidth("-1px");
		imgFooter.setHeight("-1px");
		imgFooter.setSource(new ThemeResource("img/component/embedded_icon.png"));
		imgFooter.setType(1);
		imgFooter.setMimeType("image/png");
		vlContenido.addComponent(imgFooter);
		vlContenido.setComponentAlignment(imgFooter, new Alignment(20));

		return vlContenido;
	}

}
